import type { Config } from 'tailwindcss';

const tokenColor = (name: string) => `rgb(var(--color-${name}) / <alpha-value>)`;

const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: tokenColor('surface'),
        'surface-dim': tokenColor('surface-dim'),
        'surface-bright': tokenColor('surface-bright'),
        'surface-container-lowest': tokenColor('surface-container-lowest'),
        'surface-container-low': tokenColor('surface-container-low'),
        'surface-container': tokenColor('surface-container'),
        'surface-container-high': tokenColor('surface-container-high'),
        'surface-container-highest': tokenColor('surface-container-highest'),
        'on-surface': tokenColor('on-surface'),
        'on-surface-variant': tokenColor('on-surface-variant'),
        'inverse-surface': tokenColor('inverse-surface'),
        'inverse-on-surface': tokenColor('inverse-on-surface'),
        outline: tokenColor('outline'),
        'outline-variant': tokenColor('outline-variant'),
        'surface-tint': tokenColor('surface-tint'),
        primary: tokenColor('primary'),
        'on-primary': tokenColor('on-primary'),
        'primary-container': tokenColor('primary-container'),
        'on-primary-container': tokenColor('on-primary-container'),
        'inverse-primary': tokenColor('inverse-primary'),
        secondary: tokenColor('secondary'),
        'on-secondary': tokenColor('on-secondary'),
        'secondary-container': tokenColor('secondary-container'),
        'on-secondary-container': tokenColor('on-secondary-container'),
        tertiary: tokenColor('tertiary'),
        'on-tertiary': tokenColor('on-tertiary'),
        'tertiary-container': tokenColor('tertiary-container'),
        'on-tertiary-container': tokenColor('on-tertiary-container'),
        error: tokenColor('error'),
        'on-error': tokenColor('on-error'),
        'error-container': tokenColor('error-container'),
        'on-error-container': tokenColor('on-error-container'),
        'primary-fixed': tokenColor('primary-fixed'),
        'primary-fixed-dim': tokenColor('primary-fixed-dim'),
        'on-primary-fixed': tokenColor('on-primary-fixed'),
        'on-primary-fixed-variant': tokenColor('on-primary-fixed-variant'),
        'secondary-fixed': tokenColor('secondary-fixed'),
        'secondary-fixed-dim': tokenColor('secondary-fixed-dim'),
        'on-secondary-fixed': tokenColor('on-secondary-fixed'),
        'on-secondary-fixed-variant': tokenColor('on-secondary-fixed-variant'),
        'tertiary-fixed': tokenColor('tertiary-fixed'),
        'tertiary-fixed-dim': tokenColor('tertiary-fixed-dim'),
        'on-tertiary-fixed': tokenColor('on-tertiary-fixed'),
        'on-tertiary-fixed-variant': tokenColor('on-tertiary-fixed-variant'),
        background: tokenColor('background'),
        'on-background': tokenColor('on-background'),
        'surface-variant': tokenColor('surface-variant'),
        'business-action': tokenColor('business-action'),
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
      },
      spacing: {
        unit: '8px',
        gutter: '16px',
        'margin-sm': '16px',
        'container-padding': '24px',
        'margin-lg': '32px',
        safe: 'env(safe-area-inset-bottom, 0px)',
      },
      maxWidth: {
        mobile: '420px',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': [
          '28px',
          { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        display: [
          '40px',
          { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-bold': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' },
        ],
      },
      boxShadow: {
        card: '0px 8px 24px rgba(0, 0, 0, 0.04)',
        float: '0px 4px 12px rgba(0, 0, 0, 0.10)',
        nav: '0px -4px 12px rgba(0, 0, 0, 0.04)',
      },
    },
  },
  plugins: [],
};

export default config;
